//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitCycle.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitCycle.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zugriff nicht erlaubt ähnelt.
        /// </summary>
        internal static string Access_not_allowed {
            get {
                return ResourceManager.GetString("Access not allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account ähnelt.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account konnte nicht erstellt werden ähnelt.
        /// </summary>
        internal static string Account_could_not_be_created {
            get {
                return ResourceManager.GetString("Account could not be created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account konnte leider nicht aktualisiert werden ähnelt.
        /// </summary>
        internal static string Account_could_not_be_updated {
            get {
                return ResourceManager.GetString("Account could not be updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übungen hinzufügen ähnelt.
        /// </summary>
        internal static string Add_exercise {
            get {
                return ResourceManager.GetString("Add exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willst du wirklich eine neue Woche zum Zyklus hinzufügen? ähnelt.
        /// </summary>
        internal static string Are_you_sure_to_add_a_new_week {
            get {
                return ResourceManager.GetString("Are you sure to add a new week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willst du wirklich nur mehr {0} Wochen trainieren und alle anderen Trainingstage löschen? ähnelt.
        /// </summary>
        internal static string Are_you_sure_to_only_train_x_weeks_and_delete_others {
            get {
                return ResourceManager.GetString("Are you sure to only train x weeks and delete others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurück ähnelt.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berechnen ähnelt.
        /// </summary>
        internal static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trainingszyklus abbrechen ähnelt.
        /// </summary>
        internal static string Cancel_training_cycle {
            get {
                return ResourceManager.GetString("Cancel training cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du kannst diese Übung nicht löschen, da ansonsten dein Trainingstag ohne Übungen wär ähnelt.
        /// </summary>
        internal static string Cant_delete_exercise_otherwise__training_day_empty {
            get {
                return ResourceManager.GetString("Cant delete exercise otherwise  training day empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ändern ähnelt.
        /// </summary>
        internal static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wochenanzahl ändern? ähnelt.
        /// </summary>
        internal static string Change_weekcount_asQuestion {
            get {
                return ResourceManager.GetString("Change weekcount asQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chat ähnelt.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Klicken, um die Maximalkraftwerte zu ändern ähnelt.
        /// </summary>
        internal static string Click_to_change_the_maximum_force_values {
            get {
                return ResourceManager.GetString("Click to change the maximum force values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort bestätigen ähnelt.
        /// </summary>
        internal static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbindung konnte nicht aufgebaut werden ähnelt.
        /// </summary>
        internal static string Connection_could_not_be_established {
            get {
                return ResourceManager.GetString("Connection could not be established", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuen Zyklus erstellen ähnelt.
        /// </summary>
        internal static string Create_a_new_cycle {
            get {
                return ResourceManager.GetString("Create a new cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstelle einen neuen Trainingszyklus oder überprüfe deine Internetverbindung ähnelt.
        /// </summary>
        internal static string Create_a_new_training_cycle {
            get {
                return ResourceManager.GetString("Create a new training cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FitCycle Account erstellen ähnelt.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Trainingszyklus beschreibt dein wöchtliches Training.
        ///Lege für jeden Wochentag deine Übungen fest und plane für jeden Trainingstag deine Wiederholungen, Sätze und Gewichte je Übung.
        ///Gib jetzt noch an wie viele Wochen der Zyklus dauern soll, welchen Trainingsplit du verwenden sowie wann du trainieren möchtest und schon gehts los! ähnelt.
        /// </summary>
        internal static string cycle_description {
            get {
                return ResourceManager.GetString("cycle_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zyklus dauert {0} Wochen ähnelt.
        /// </summary>
        internal static string Cycle_lasts_x_weeks {
            get {
                return ResourceManager.GetString("Cycle lasts x weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dashboard ähnelt.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intensität Deload-Week ähnelt.
        /// </summary>
        internal static string Deload_Week_intensity {
            get {
                return ResourceManager.GetString("Deload Week intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willst du deine Änderungen speichern? ähnelt.
        /// </summary>
        internal static string Do_you_want_to_save_changes {
            get {
                return ResourceManager.GetString("Do you want to save changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profil bearbeiten ähnelt.
        /// </summary>
        internal static string Edit_profile {
            get {
                return ResourceManager.GetString("Edit profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail oder Passwort inkorrekt ähnelt.
        /// </summary>
        internal static string Email_or_password_incorrect {
            get {
                return ResourceManager.GetString("Email or password incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ende ähnelt.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Laden ähnelt.
        /// </summary>
        internal static string error_at_loading {
            get {
                return ResourceManager.GetString("error at loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übungsart ähnelt.
        /// </summary>
        internal static string Exercise_type {
            get {
                return ResourceManager.GetString("Exercise type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle eine Übung aus, um Details anzuzeigen.
        ///Wische nach links um eine Übung zu löschen. ähnelt.
        /// </summary>
        internal static string ExercisePage_Description {
            get {
                return ResourceManager.GetString("ExercisePage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übungen ähnelt.
        /// </summary>
        internal static string Exercises {
            get {
                return ResourceManager.GetString("Exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übungen konnten nicht geladen werden. Überprüfe deine Internetverbindung ähnelt.
        /// </summary>
        internal static string Exercises_could_not_be_loaded {
            get {
                return ResourceManager.GetString("Exercises could not be loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übungen: ähnelt.
        /// </summary>
        internal static string Exercises_withDots {
            get {
                return ResourceManager.GetString("Exercises_withDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übung beenden ähnelt.
        /// </summary>
        internal static string Finish_exercise {
            get {
                return ResourceManager.GetString("Finish exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training beenden ähnelt.
        /// </summary>
        internal static string Finish_training {
            get {
                return ResourceManager.GetString("Finish training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FitCycleUser ähnelt.
        /// </summary>
        internal static string FitCycleUser {
            get {
                return ResourceManager.GetString("FitCycleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zum Login ähnelt.
        /// </summary>
        internal static string GoTo_Login {
            get {
                return ResourceManager.GetString("GoTo Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intensität Intro-Week ähnelt.
        /// </summary>
        internal static string Intro_Week_intensity {
            get {
                return ResourceManager.GetString("Intro Week intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die kg ähnelt.
        /// </summary>
        internal static string kg {
            get {
                return ResourceManager.GetString("kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zyklus aus Archiv laden ähnelt.
        /// </summary>
        internal static string Load_cycle_from_archive {
            get {
                return ResourceManager.GetString("Load cycle from archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen konnten nicht vom Server geladen werden. Bitte wende dich an den AppSupport. ähnelt.
        /// </summary>
        internal static string Load_settings_failded_Please_contact_support {
            get {
                return ResourceManager.GetString("Load settings failded Please contact support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen werden geladen... ähnelt.
        /// </summary>
        internal static string Loading_settings {
            get {
                return ResourceManager.GetString("Loading settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login fehlgeschlagen ähnelt.
        /// </summary>
        internal static string Login_failed {
            get {
                return ResourceManager.GetString("Login failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login erfolgreich ähnelt.
        /// </summary>
        internal static string Login_successful {
            get {
                return ResourceManager.GetString("Login successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logout ähnelt.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir suchen nach deinen Trainingszyklen... ähnelt.
        /// </summary>
        internal static string Looking_for_your_training_cycles {
            get {
                return ResourceManager.GetString("Looking for your training cycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mailadresse ähnelt.
        /// </summary>
        internal static string Mailadress {
            get {
                return ResourceManager.GetString("Mailadress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximalkraft ähnelt.
        /// </summary>
        internal static string Maximum_force {
            get {
                return ResourceManager.GetString("Maximum force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximalkraftwerte ähnelt.
        /// </summary>
        internal static string Maximum_force_Values {
            get {
                return ResourceManager.GetString("Maximum force Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nachricht ähnelt.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Muskelgruppe ähnelt.
        /// </summary>
        internal static string muscle_Group {
            get {
                return ResourceManager.GetString("muscle Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mein neuer Zyklus ähnelt.
        /// </summary>
        internal static string My_new_cycle {
            get {
                return ResourceManager.GetString("My new cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mein Trainingszyklus dauert {0} Wochen ähnelt.
        /// </summary>
        internal static string My_training_cycle_lasts_x_weeks {
            get {
                return ResourceManager.GetString("My training cycle lasts x weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu hier? Sammle alle Daten in deinem persönlichen Profil ähnelt.
        /// </summary>
        internal static string New_here__Collect_data_in_profile {
            get {
                return ResourceManager.GetString("New_here?_Collect_data_in_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nächste Übung ähnelt.
        /// </summary>
        internal static string Next_exercise {
            get {
                return ResourceManager.GetString("Next exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nächster Trainingstag ähnelt.
        /// </summary>
        internal static string Next_training_day {
            get {
                return ResourceManager.GetString("Next training day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es konnte kein aktueller Zyklus gefunden werden ähnelt.
        /// </summary>
        internal static string No_current_cycle_found {
            get {
                return ResourceManager.GetString("No current cycle found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keinen aktuellen Trainingszyklus gefunden ähnelt.
        /// </summary>
        internal static string No_current_training_cycle_found {
            get {
                return ResourceManager.GetString("No current training cycle found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine aktuellen Trainingstage gefunden ähnelt.
        /// </summary>
        internal static string No_current_training_days_found {
            get {
                return ResourceManager.GetString("No current training days found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Übungen gefunden ähnelt.
        /// </summary>
        internal static string No_exercises_found {
            get {
                return ResourceManager.GetString("No exercises found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine passende Übung gefunden ähnelt.
        /// </summary>
        internal static string No_suitable_exercise_found {
            get {
                return ResourceManager.GetString("No suitable exercise found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Training ähnelt.
        /// </summary>
        internal static string no_training {
            get {
                return ResourceManager.GetString("no training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Trainingstage gefunden. Zyklus konnte nicht abgebrochen werden. ähnelt.
        /// </summary>
        internal static string No_training_days_found__Cycle_could_not_canceled {
            get {
                return ResourceManager.GetString("No training days found. Cycle could not canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oh! Ja, bitte ähnelt.
        /// </summary>
        internal static string Oh_Yes_please {
            get {
                return ResourceManager.GetString("Oh Yes please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ups, es konnte leider kein neuer Zyklus erstellt werden ähnelt.
        /// </summary>
        internal static string Oops__unfortunately_we_couldn_t_create_a_new_cycle {
            get {
                return ResourceManager.GetString("Oops, unfortunately we couldn\'t create a new cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ups, Zyklus-Verlängerung fehlgeschlagen ähnelt.
        /// </summary>
        internal static string Oops_cycle_extension_failed {
            get {
                return ResourceManager.GetString("Oops cycle extension failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ähnelt.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort konnte nicht geändert werden ähnelt.
        /// </summary>
        internal static string Password_could_not_be_changed {
            get {
                return ResourceManager.GetString("Password could not be changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ungültig ähnelt.
        /// </summary>
        internal static string Password_invalid {
            get {
                return ResourceManager.GetString("Password invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwörter stimmen nicht überein ähnelt.
        /// </summary>
        internal static string Passwords_do_not_match {
            get {
                return ResourceManager.GetString("Passwords do not match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geplant: ähnelt.
        /// </summary>
        internal static string Planed_withDots {
            get {
                return ResourceManager.GetString("Planed_withDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte füge Übungen deiner Liste hinzu oder überprüfe deine Internetverbindung ähnelt.
        /// </summary>
        internal static string Please_add_exercises_to_your_list {
            get {
                return ResourceManager.GetString("Please add exercises to your list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte fülle alle Daten vollständig und korrekt aus ähnelt.
        /// </summary>
        internal static string Please_fill_in_all_data_completely {
            get {
                return ResourceManager.GetString("Please fill in all data completely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diese Übungen stehen heute am Programm ähnelt.
        /// </summary>
        internal static string Program_contains_these_exercises {
            get {
                return ResourceManager.GetString("Program contains these exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Progressive Overload ähnelt.
        /// </summary>
        internal static string Progressive_Overload {
            get {
                return ResourceManager.GetString("Progressive Overload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übung entfernen ähnelt.
        /// </summary>
        internal static string Remove_exercise {
            get {
                return ResourceManager.GetString("Remove exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wiederholungen ähnelt.
        /// </summary>
        internal static string Repetitions {
            get {
                return ResourceManager.GetString("Repetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wdh. ähnelt.
        /// </summary>
        internal static string Repetitions_ShortCut {
            get {
                return ResourceManager.GetString("Repetitions_ShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erneut versuchen ähnelt.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RM - Formel ähnelt.
        /// </summary>
        internal static string RM_formula {
            get {
                return ResourceManager.GetString("RM-formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RPE ähnelt.
        /// </summary>
        internal static string RPE {
            get {
                return ResourceManager.GetString("RPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern? ähnelt.
        /// </summary>
        internal static string Save_asQuestion {
            get {
                return ResourceManager.GetString("Save_asQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchen ähnelt.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trainingszyklus auswählen ähnelt.
        /// </summary>
        internal static string Select_training_cycle {
            get {
                return ResourceManager.GetString("Select training cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trainingstage und Übungen auswählen ähnelt.
        /// </summary>
        internal static string Select_training_days_and_exercises {
            get {
                return ResourceManager.GetString("Select training days and exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Satz ähnelt.
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll das Passwort geändert werden? \r\n(Neuerlicher Login erforderlich) ähnelt.
        /// </summary>
        internal static string Should_the_password_be_changed {
            get {
                return ResourceManager.GetString("Should the password be changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuellen Trainingszyklus anzeigen ähnelt.
        /// </summary>
        internal static string Show_current_training_cycle {
            get {
                return ResourceManager.GetString("Show current training cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übung starten ähnelt.
        /// </summary>
        internal static string Start_exercise {
            get {
                return ResourceManager.GetString("Start exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause starten ähnelt.
        /// </summary>
        internal static string Start_Pause {
            get {
                return ResourceManager.GetString("Start Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training starten ähnelt.
        /// </summary>
        internal static string Start_training {
            get {
                return ResourceManager.GetString("Start training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Zylus startet am ähnelt.
        /// </summary>
        internal static string The_cycle_starts_on {
            get {
                return ResourceManager.GetString("The cycle starts on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Mail-Adresse existiert bereits ähnelt.
        /// </summary>
        internal static string The_email_address_exists {
            get {
                return ResourceManager.GetString("The email address exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trainingspause (min) ähnelt.
        /// </summary>
        internal static string Training_break_in_min {
            get {
                return ResourceManager.GetString("Training break_in_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle den Split für den Trainngstag aus und wähle anschließend alle Übungen, die du an diesem Tag trainieren möchtest.
        ///Sollte eine Übung nicht dabei sein, gehe zu deiner Übungsübersicht. ähnelt.
        /// </summary>
        internal static string training_day_description {
            get {
                return ResourceManager.GetString("training day description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trainingstage konnten nicht geladen werden ähnelt.
        /// </summary>
        internal static string Training_days_could_not_be_loaded {
            get {
                return ResourceManager.GetString("Training days could not be loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trainingssplit ähnelt.
        /// </summary>
        internal static string Training_Split {
            get {
                return ResourceManager.GetString("Training Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training heute ähnelt.
        /// </summary>
        internal static string Training_today {
            get {
                return ResourceManager.GetString("Training today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trainingstage doppelt vorhanden. Bitte wende dich an den AppSupport. ähnelt.
        /// </summary>
        internal static string Trainingdays_twice_Please_contact_support {
            get {
                return ResourceManager.GetString("Trainingdays twice Please contact support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trainingszeit ähnelt.
        /// </summary>
        internal static string Trainingtime {
            get {
                return ResourceManager.GetString("Trainingtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UserID nicht vorhanden ähnelt.
        /// </summary>
        internal static string UserID_not_available {
            get {
                return ResourceManager.GetString("UserID not available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Werte des letzten Training anzeigen ähnelt.
        /// </summary>
        internal static string View_values_from_last_training {
            get {
                return ResourceManager.GetString("View values from last training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir checken deine Trainingstage... ähnelt.
        /// </summary>
        internal static string We_check_your_training_days {
            get {
                return ResourceManager.GetString("We check your training days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir laden deinen persönlichen Trainingszyklus ähnelt.
        /// </summary>
        internal static string We_load_your_personal_training_cycle {
            get {
                return ResourceManager.GetString("We load your personal training cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Woche ähnelt.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gewicht ähnelt.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gewichtsschritte ähnelt.
        /// </summary>
        internal static string Weight_increments {
            get {
                return ResourceManager.GetString("Weight increments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie soll dein Trainingstag aussehen? ähnelt.
        /// </summary>
        internal static string What_should_your_training_day_look_like {
            get {
                return ResourceManager.GetString("What should your training day look like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willst du die App schließen? ähnelt.
        /// </summary>
        internal static string Would_you_like_to_exit_from_application {
            get {
                return ResourceManager.GetString("Would you like to exit from application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja, Trainingstage jetzt erstellen ähnelt.
        /// </summary>
        internal static string Yes_create_training_days {
            get {
                return ResourceManager.GetString("Yes create training days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja, Trainingstage löschen ähnelt.
        /// </summary>
        internal static string Yes_delete_training_days {
            get {
                return ResourceManager.GetString("Yes delete training days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Übungen werden durchsucht... ähnelt.
        /// </summary>
        internal static string Your_exercises_are_searched {
            get {
                return ResourceManager.GetString("Your exercises are searched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Übungen von heute ähnelt.
        /// </summary>
        internal static string Your_exercises_from_today {
            get {
                return ResourceManager.GetString("Your exercises from today", resourceCulture);
            }
        }
    }
}
